name: CI

on:
  pull_request:
  push:

jobs:
  
  centos7:
    runs-on: ubuntu-latest
    container: centos:centos7
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          yum install epel-release
          yum install -y make file automake libtool gcc-c++ openssl-devel gsoap-devel gsoap expat-devel bison

      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make
