name: CI

on:
  pull_request:
  push:

jobs:
  
  centos7:
    runs-on: ubuntu-latest
    container: centos:centos7
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          yum install -y epel-release
          yum install -y make file automake libtool gcc-c++ openssl-devel gsoap-devel gsoap expat-devel bison

      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make

  centos9:
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream9
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          yum install -y epel-release
          yum install -y make file automake libtool gcc-c++ openssl-devel gsoap-devel gsoap expat-devel bison

      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make

  ubuntu2004:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          apt update
          apt install make automake libtool pkg-config g++ libssl-dev libgsoap-dev gsoap libexpat-dev

      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make
